server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huijunsy/microservicecloud-config.git #GitHub上面的git仓库名字
          force-pull: true
          clone-on-start: true
 

